parameters: {}
environment: {}
packages:
  - name: p
    environment: {
      LOG_DESTINATIONS: "${LOG_DESTINATIONS}"
    }
    parameters: {}
    actions:
      - name: r
        main: ''
        runtime: 'go:default'
        environment: {
          LOG_DESTINATIONS: "${LOG_DESTINATIONS}"
        }
        parameters: {}
