parameters: {}
environment: {
  LOG_DESTINATIONS: '${LOG_DESTINATIONS}',
  LOG_LEVEL: '${LOG_LEVEL}',
  HEARTBEAT_TOKEN: '${HEARTBEAT_TOKEN}',
  HEARTBEAT_TARGET: '${HEARTBEAT_TARGET}',
  HEARTBEAT_TARGET_TIMEOUT: '${HEARTBEAT_TARGET_TIMEOUT}'
}
packages:
  - name: pxy
    environment: {}
    parameters: {}
    actions:
      - name: redirect
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}
