parameters: {}
environment: {
  LOG_DESTINATIONS: '${LOG_DESTINATIONS}',
  LOG_LEVEL: '${LOG_LEVEL}',
  HEARTBEAT_TOKEN: '${HEARTBEAT_TOKEN}'
}
packages:
  - name: p
    environment: {}
    parameters: {}
    actions:
      - name: r
        main: ''
        runtime: 'go:1.20'
        environment: {}
        parameters: {}
