name: Update App

on:
 push:
   branches: [main]

permissions:
  contents: read

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      HEARTBEAT_TOKEN: ${{ secrets.HEARTBEAT_TOKEN }}
      HEARTBEAT_TARGET: ${{ vars.HEARTBEAT_TARGET }}
      HEARTBEAT_TARGET_TIMEOUT: ${{ vars.HEARTBEAT_TARGET_TIMEOUT }}
      LOG_DESTINATIONS: ${{ secrets.LOG_DESTINATIONS }}
      LOG_LEVEL: ${{ vars.LOG_LEVEL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install doctl
        uses: digitalocean/action-doctl@3cb3953159719656269e044e0e24ca16dd2a690f # v2.5.2
        with:
          token: ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}
      - name: Install the serverless extension for doctl and connect
        run: doctl serverless install && doctl serverless connect
      - name: Deploy the serverless function
        run: doctl serverless deploy .
